### ISSUE TITLE
Pypi deployment using Travis CI

### ISSUE THREAD

**Issue by scls19fr** [python-windrose/windrose#110]
Deployment to Pypi of new release using Travis CI should be done using:
https://docs.travis-ci.com/user/deployment/pypi/

**Comment by ocefpaf** [comment]
@scls19fr you can accomplish that by adding the following lines at the end of your `.travis.yaml` file:

```yaml
deploy:
  skip_cleanup: true
  provider: pypi
  user: PYPI_USERNAME
  password:
    secure: TRAVIS_ENCRYPTED_PYPI_PASSWORD
  distributions: sdist bdist_wheel
  upload_docs: no
  on:
    repo: python-windrose/windrose
    tags: true
    all_branches: master
    condition: '$TEST_TARGET == "default"'
```

You will need to add the `PYPI_USERNAME` and the `TRAVIS_ENCRYPTED_PYPI_PASSWORD`.
The latter can be generated with Travis-CI CLI and the command:

```shell
travis encrypt -r python-windrose/windrose
```
